## Задания на повторение материала

### Задание 1

In [5]:
import numpy as np
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Задание 2

In [16]:
import numpy as np
a = np.arange(12, 24)
print()
a1 = a.reshape(3, 4)
print(f'Размерность a1: {format(a1.ndim)}')
print(a1)
print()
a2 = a.reshape(4, 3)
print(f'Размерность a2: {format(a2.ndim)}')
print(a2)
print()
a3 = np.random.choice(a, (2, 2))
print(f'Размерность a3: {format(a3.ndim)}')
print(a3)
print()
a4 = np.random.choice(a, (5, 2))
print(f'Размерность a4: {format(a4.ndim)}')
print(a4)
print()
a5 = np.random.choice(a, (2, 4))
print(f'Размерность a5: {format(a5.ndim)}')
print(a5)


Размерность a1: 2
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Размерность a2: 2
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

Размерность a3: 2
[[18 12]
 [19 20]]

Размерность a4: 2
[[16 22]
 [22 20]
 [15 16]
 [20 14]
 [21 15]]

Размерность a5: 2
[[12 12 18 21]
 [20 22 16 19]]


### Задание 3

In [19]:
import numpy as np
a = np.arange(12, 24)
print()
a1 = a.reshape(3, -1)
print(f'Размерность a1: {format(a1.ndim)}')
print(a1)
print()
a2 = a.reshape(4, -1)
print(f'Размерность a2: {format(a2.ndim)}')
print(a2)
print()
a3 = a.reshape(12, -1)
print(f'Размерность a3: {format(a3.ndim)}')
print(a3)
print()
a4 = a.reshape(-1, 2)
print(f'Размерность a4: {format(a4.ndim)}')
print(a4)
print()
a5 = a.reshape(-1, 6)
print(f'Размерность a5: {format(a5.ndim)}')
print(a5)


Размерность a1: 2
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Размерность a2: 2
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

Размерность a3: 2
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]

Размерность a4: 2
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

Размерность a5: 2
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


### Задание 4 

In [23]:
# Можно ли массив Numpy из 12 сторок и 1 столбца назвать одномерным? - нет
import numpy as np
a = np.random.sample((12, 1))
b = format(a.ndim)
print(a)
print(f'Размерность а: {b}')

[[0.92571869]
 [0.0723562 ]
 [0.16784377]
 [0.44054004]
 [0.14400219]
 [0.20337561]
 [0.77502481]
 [0.86508221]
 [0.67090604]
 [0.88328497]
 [0.53300217]
 [0.64442236]]
Размерность а: 2


### Задание 5

In [26]:
import numpy as np
a = np.random.randn(3,4)
print(a)
print()
b = a.flatten()
print(b)
print()
print(f'размер а: {a.size}')
print(f'размер b: {b.size}')

[[-0.30272628 -1.16339648  0.70865216  0.83387537]
 [-0.27369403 -0.87852531  0.49182009  0.18809972]
 [ 0.41547188  0.28239015  0.36333923 -0.09992744]]

[-0.30272628 -1.16339648  0.70865216  0.83387537 -0.27369403 -0.87852531
  0.49182009  0.18809972  0.41547188  0.28239015  0.36333923 -0.09992744]

размер а: 12
размер b: 12


### Задание 6

In [27]:
import numpy as np
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


### Задание 7

In [40]:
import numpy as np
a = np.arange(20, 0, -2)
b = np.arange(20, 1, -2).reshape(1, 10)
print(a)
print()
print(b)
print()
print(f'Размерность а: {format(a.ndim)}')
print(f'Размерность b: {format(b.ndim)}')
print('Массив а - одномерный, массив b - двумерный')

[20 18 16 14 12 10  8  6  4  2]

[[20 18 16 14 12 10  8  6  4  2]]

Размерность а: 1
Размерность b: 2
Массив а - одномерный, массив b - двумерный


### Задание 8

In [45]:
import numpy as np
a = np.zeros((2, 2))
b = np.ones((3, 2))
d = np.concatenate((a, b), axis=0)
print(d)
print(f'Размер d = {d.size}')

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Размер d = 10


### Задание 9

In [55]:
import numpy as np
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
print(B)
print(f'Размер матрицы B: {format(B.shape)}') 
print()
d = np.linalg.det(B)
print(f'Так как определитель матрицы В = {d}, вычислить обратную матрицу для матрицы В нельзя.')

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Размер матрицы B: (4, 4)

Так как определитель матрицы В = 0.0, вычислить обратную матрицу для матрицы В нельзя.


### Задание 10

In [6]:
import numpy as np
np.random.seed(42)
a = np.random.randint(1, 10)
print(a)

7


### Задание 11

In [10]:
import numpy as np
c = np.random.randint(0, 16, size=16)
c

array([13, 14, 13,  2, 11,  6,  3, 15,  8,  2,  4,  2,  6,  4,  8,  6])

### Задание 12

In [18]:
import numpy as np
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
c = np.random.randint(0, 16, size=16)
C = c.reshape(4,4)

D = 10 * C + B
print('Матрица D:')
print(D)
print()
d = np.linalg.det(D)
print(f'Определитель матрицы D = {d}')
r = np.linalg.matrix_rank(D)
print(f'Ранг матрицы D = {r}')
print()
if d > 0:
    D_inv = np.linalg.inv(D)
    print("обратная матрица D_inv для матрицы D")
    print(D_inv)
else:
    print('Определитель матрицы равен 0, обратную матрицу посчитать нельзя')


Матрица D:
[[ 85  84 133  42]
 [ 14 200 146 182]
 [153 156 189 232]
 [142 192 262 402]]

Определитель матрицы D = -253137600.0000001
Ранг матрицы D = 4

обратная матрица D_inv для матрицы D
[[-0.00482173 -0.0037431   0.01618693 -0.00714331]
 [-0.00610814  0.00770664  0.01148672 -0.00948006]
 [ 0.0163677  -0.00217874 -0.01770579  0.0094946 ]
 [-0.00604699 -0.00093862  0.00033563  0.00335059]]


### Задание 13

In [34]:
import numpy as np
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
c = np.random.randint(0, 16, size=16)
C = c.reshape(4,4)
D = 10 * C + B
d = np.linalg.det(D)
if d != 0:
    D_inv = np.linalg.inv(D)
    print("обратная матрица D_inv для матрицы D")
    print(D_inv)
    print()
    print('Замена в матрице D_inv отрицательных элементов на 0, а положительных на 1')
    D_inv[D_inv <= 0] = 0
    D_inv[D_inv > 0] = 1
    print('матрица D_inv c 0 и 1')
    print(D_inv)
    print()
    print('Матрица В:')
    print(B)
    print('Матрица С:')
    print(C)
    print()
    E = np.where(D_inv == 1, B, C)
    print('Матрица E: если элемент матрицы D_inv = 1, то значение из матрицы В; если = 0, то значение из матрицы С.')
    print(E)
else:
    print('Определитель матрицы равен 0, обратную матрицу посчитать нельзя')


обратная матрица D_inv для матрицы D
[[ 0.11413648  0.10794998  0.01630703 -0.10643988]
 [-0.0255709  -0.03279377 -0.00082364  0.02765889]
 [-0.03775592 -0.031511   -0.01717956  0.04214019]
 [-0.00554448 -0.00244424  0.00804651 -0.0012072 ]]

Замена в матрице D_inv отрицательных элементов на 0, а положительных на 1
матрица D_inv c 0 и 1
[[1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

Матрица В:
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Матрица С:
[[ 7 15  6  1]
 [ 7  0 10 11]
 [ 8  8  1  6]
 [14 13  9  2]]

Матрица E: если элемент матрицы D_inv = 1, то значение из матрицы В; если = 0, то значение из матрицы С.
[[  5  14  23   1]
 [  7   0  10 122]
 [  8   8   1 212]
 [ 14  13 212   2]]
