## Тема: Вычисления с помощью Numpy
### задание 1


In [10]:
import numpy as np
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
print('Массив:')
print(a)
mean_a = a.mean(axis=0)
print(f'Средние значения по столбцам: {mean_a}')

Массив:
[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Средние значения по столбцам: [2.  8.4]


### задание 2

In [12]:
import numpy as np
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
mean_a = a.mean(axis=0)
a_centered = a - mean_a
print('Из массива а отняли средние значения по столбцам:')
print(a_centered)

Из массива а отняли средние значения по столбцам:
[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


### задание 3

In [24]:
import numpy as np
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
mean_a = a.mean(axis=0)
a_centered = a - mean_a
a0 = a_centered[0:5, 0].copy()
a1 = a_centered[0:5, 1].copy()
print(a0)
print(a1)
a_centered_sp = a0 @ a1
N = 5 # число наблюдений
print(f'Скалярное произведение столбцов: {a_centered_sp}')
print(f'Несмещенная оценка ковариации: {a_centered_sp / (N - 1)}')

[-1.  0.  1.  1. -1.]
[-2.4 -0.4  2.6  1.6 -1.4]
Скалярное произведение столбцов: 8.0
Несмещенная оценка ковариации: 2.0


### задание 4**

In [23]:
import numpy as np
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
aT = a.T # транспонированный массив а
m = np.cov(aT)
print('Ковариационная матрица: ')
print(m)
a_cov = m[0, 1]
print(f'Ковариация = {a_cov}')

Ковариационная матрица: 
[[1.  2. ]
 [2.  4.3]]
Ковариация = 2.0
